import './globals.css';
import { Inter } from 'next/font/google';
import Loading from '@/app/loading';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout(props: {
    children: React.ReactNode;
    analytics: React.ReactNode;
    team: React.ReactNode;
}) {
    console.log('props');
    console.log(props);
    return (
        <html lang="en">
            <body className={inter.className}>
                <Suspense fallback={<Loading />}>
                    RootLayout123
                    {/* {props.children} */}
                    {props.analytics}
                    {props.team}
                </Suspense>
            </body>
        </html>
    );
}
